### ISSUE TITLE
Don't create PR if identical one exists

### ISSUE THREAD

**Issue by dracos** [everypolitician/rebuilder#29]
Instead of always creating a PR regardless, and having https://github.com/everypolitician/pull_request_cleaner delete the old one, could this check whether a PR exists with identical contents and not bother doing anything? Or not worth it?

**Comment by davewhiteland** [comment]
yup, or "not bother doing anything"  might be better leaving a comment to bump the date, since it's relevant to know the incoming data is _still_ extant today even if the PR was made a week ago

**Comment by tmtmtmtm** [comment]
I don't think this would buy us much, as the question isn't really whether the new PR is identical. The pattern is quite often that we have one PR with some new changes one day (but that we haven't merged yet), and then the next day we get a new PR with those changes — and some more. In that sort of case we'll want the new one to supersede the intermediate one and close it etc, so will still need the workflow we already have anyway. Short-circuiting that if a new PR is identical seems like it would just add extra complexity to the Rebuilder for no real value.
