### ISSUE TITLE
Include source name in pull request title

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/rebuilder#59]
# Problem

When a rebuild is done for a specific source there's no clear indication of that in the resulting pull request.

# Proposed solution

Add the source name to the title and/or body of the pull request that gets created by the rebuilder.

# Related issues

Original issue was https://github.com/everypolitician/everypolitician/issues/380.

**Comment by tmtmtmtm** [comment]
The wider issue here isn't so much clarity, but that the helpful bot will see multiple PRs with the same title as being duplicates and close the earlier ones…

**Comment by chrismytton** [comment]
I've had a stab at doing this in https://github.com/everypolitician/rebuilder/pull/61, but writing regression tests for it is proving to be very difficult. I've opened #62 to track a wider refactoring of the problem method in the code. Once that's been at least partially done it should be easier to do this change in a testable way.
